***************************************************************************************************** 
* WARNING: The 2021 software stack is not available on the 'genoa' partition.
Please use the 2022 * 
* software stack. * 
* * 
* If you have any question, please contact us via
http://servicedesk.surfsara.nl. * 
***************************************************************************************************** 
To connect to the notebook type the following command from your local terminal:
ssh -J qiahan@int5-pub.snellius.surf.nl qiahan@fcn39.local.snellius.surf.nl -L 5069:localhost:5069

After connection is established in your local browser go to the address:
http://localhost:5069
[I 2023-09-05 18:11:25.335 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-05 18:11:25.850 ServerApp] Package dask_labextension took 0.5139s to import
[W 2023-09-05 18:11:25.850 ServerApp] A `_jupyter_server_extension_points` function was not found in dask_labextension. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 18:11:26.303 ServerApp] Package ipyparallel took 0.4528s to import
[W 2023-09-05 18:11:26.304 ServerApp] A `_jupyter_server_extension_points` function was not found in ipyparallel. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 18:11:26.307 ServerApp] Package jupyter_server_fileid took 0.0031s to import
[I 2023-09-05 18:11:26.309 ServerApp] Package jupyter_server_mathjax took 0.0015s to import
[I 2023-09-05 18:11:26.309 ServerApp] Package jupyter_server_proxy took 0.0000s to import
[I 2023-09-05 18:11:26.314 ServerApp] Package jupyter_server_terminals took 0.0048s to import
[I 2023-09-05 18:11:26.354 ServerApp] Package jupyter_server_ydoc took 0.0392s to import
[I 2023-09-05 18:11:26.371 ServerApp] Package jupyterlab_git took 0.0165s to import
[I 2023-09-05 18:11:26.371 ServerApp] Package nbclassic took 0.0000s to import
[W 2023-09-05 18:11:26.373 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 18:11:26.374 ServerApp] Package nbdime took 0.0000s to import
[I 2023-09-05 18:11:26.374 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-05 18:11:26.374 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 18:11:26.375 ServerApp] dask_labextension | extension was successfully linked.
[I 2023-09-05 18:11:26.375 ServerApp] ipyparallel | extension was successfully linked.
[I 2023-09-05 18:11:26.382 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-09-05 18:11:26.390 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-09-05 18:11:26.390 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2023-09-05 18:11:26.397 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-05 18:11:26.403 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-09-05 18:11:26.456 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-05 18:11:26.456 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-09-05 18:11:26.463 ServerApp] nbclassic | extension was successfully linked.
[I 2023-09-05 18:11:26.463 ServerApp] nbdime | extension was successfully linked.
[I 2023-09-05 18:11:26.473 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-09-05 18:11:26.572 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-09-05 18:11:26.575 ServerApp] dask_labextension | extension was successfully loaded.
[I 2023-09-05 18:11:26.577 ServerApp] Loading IPython parallel extension
[I 2023-09-05 18:11:26.578 ServerApp] ipyparallel | extension was successfully loaded.
[I 2023-09-05 18:11:26.578 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-09-05 18:11:26.578 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /gpfs/work2/0/ttse0619/qianqian
[I 2023-09-05 18:11:26.579 FileIdExtension] ArbitraryFileIdManager : Configured database path: /gpfs/home2/qiahan/.local/share/jupyter/file_id_manager.db
[I 2023-09-05 18:11:26.579 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-09-05 18:11:26.579 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-09-05 18:11:26.580 FileIdExtension] Attached event listeners.
[I 2023-09-05 18:11:26.580 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-09-05 18:11:26.581 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2023-09-05 18:11:26.599 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2023-09-05 18:11:26.600 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-09-05 18:11:26.601 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-09-05 18:11:26.609 LabApp] JupyterLab extension loaded from /home/qiahan/.conda/envs/mamba/envs/emulator/lib/python3.9/site-packages/jupyterlab
[I 2023-09-05 18:11:26.609 LabApp] JupyterLab application directory is /gpfs/home2/qiahan/.conda/envs/mamba/envs/emulator/share/jupyter/lab
[I 2023-09-05 18:11:26.612 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-09-05 18:11:26.618 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2023-09-05 18:11:26.624 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-09-05 18:11:26.872 ServerApp] nbdime | extension was successfully loaded.
[I 2023-09-05 18:11:26.873 ServerApp] Serving notebooks from local directory: /gpfs/work2/0/ttse0619/qianqian
[I 2023-09-05 18:11:26.873 ServerApp] Jupyter Server 2.5.0 is running at:
[I 2023-09-05 18:11:26.873 ServerApp] http://localhost:5069/lab?token=12c26b64ef142091bbd2ccfac5a6c54fc1adfd95e9011870
[I 2023-09-05 18:11:26.873 ServerApp]     http://127.0.0.1:5069/lab?token=12c26b64ef142091bbd2ccfac5a6c54fc1adfd95e9011870
[I 2023-09-05 18:11:26.873 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-09-05 18:11:26.878 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///gpfs/home2/qiahan/.local/share/jupyter/runtime/jpserver-129046-open.html
    Or copy and paste one of these URLs:
        http://localhost:5069/lab?token=12c26b64ef142091bbd2ccfac5a6c54fc1adfd95e9011870
        http://127.0.0.1:5069/lab?token=12c26b64ef142091bbd2ccfac5a6c54fc1adfd95e9011870
[I 2023-09-05 18:12:01.790 LabApp] Generating new user for token-authenticated request: 645c175e4c174941984ce8a87c38c0f0
[I 2023-09-05 18:12:09.284 LabApp] Build is up to date
[I 2023-09-05 18:12:19.291 ServerApp] Kernel started: a07084a9-cdbd-48a0-a22d-fd5d4a0aaaa2
[I 2023-09-05 18:12:19.299 ServerApp] Kernel started: 6b866824-a4c2-4727-8767-086aa96168b9
[I 2023-09-05 18:12:19.985 ServerApp] Connecting to kernel 6b866824-a4c2-4727-8767-086aa96168b9.
[I 2023-09-05 18:12:20.002 ServerApp] Connecting to kernel a07084a9-cdbd-48a0-a22d-fd5d4a0aaaa2.
[I 2023-09-05 18:12:20.056 ServerApp] Connecting to kernel 6b866824-a4c2-4727-8767-086aa96168b9.
[I 2023-09-05 18:12:20.142 ServerApp] Connecting to kernel 6b866824-a4c2-4727-8767-086aa96168b9.
[I 2023-09-05 18:13:08.404 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 18:13:23.936 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 18:15:24.929 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
2023-09-05 18:15:36,032 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 8, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x153c1bb92280>, <function predictFlux at 0x153c1bb924c0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [6.49429860e+01, 6.48050675e+01, 6.49085402e+01, ...,
          6.65975723e+01, 6.84245138e+01, 7.02514563e+01],
         [6.70111756e+01, 6.69767380e+01, 6.70802088e+01, ...,
          6.95620794e+01, 7.18370829e+01, 7.40432682e+01],
         [6.88381271e+01, 6.89415979e+01, 6.90449972e+01, ...,
          7.18715982e+01, 7.43190317e+01, 7.68354177e+01]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
2023-09-05 18:15:48,733 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 0, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x154a4529d8b0>, <function predictFlux at 0x154a4529d9d0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05, -6.94444461e-05, -6.94444461e-05],
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05, -6.94444461e-05, -6.94444461e-05],
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

2023-09-05 18:15:49,034 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 6, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x147430a105e0>, <function predictFlux at 0x147430a10dc0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

2023-09-05 18:15:49,470 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 1, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x154a440941f0>, <function predictFlux at 0x154a3f97d310>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [1.95122223e+01, 1.79289589e+01, 1.66025009e+01, ...,
          9.37097168e+00, 9.24263763e+00, 9.11416626e+00],
         [1.94694443e+01, 1.79718056e+01, 1.66881256e+01, ...,
          9.24263763e+00, 9.11416626e+00, 8.94305420e+00],
         [1.91698608e+01, 1.79289589e+01, 1.68163910e+01, ...,
          8.90027618e+00, 8.77194214e+00, 8.55791473e+00]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

2023-09-05 18:15:49,685 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 4, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x153c1f474af0>, <function predictFlux at 0x153c1f4741f0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [3.66786652e+02, 3.63299438e+02, 3.58317230e+02, ...,
          1.64524719e+02, 1.65645554e+02, 1.67264725e+02],
         [3.82977783e+02, 3.79739441e+02, 3.74632782e+02, ...,
          1.74114716e+02, 1.76107498e+02, 1.77851105e+02],
         [3.96054443e+02, 3.93065552e+02, 3.88333344e+02, ...,
          1.88561951e+02, 1.91052780e+02, 1.93792770e+02]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

2023-09-05 18:15:49,986 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 2, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x14f244ca34c0>, <function predictFlux at 0x14f244c96c10>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [ 4.00766937e+02,  4.01652374e+02,  4.02215820e+02, ...,
           4.34975830e+02,  4.35458893e+02,  4.35941803e+02],
         [ 4.01893890e+02,  4.02698761e+02,  4.03342773e+02, ...,
           4.37309998e+02,  4.37712646e+02,  4.38275970e+02],
         [ 4.02940277e+02,  4.03745148e+02,  4.04469574e+02, ...,
           4.39805420e+02
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

2023-09-05 18:15:50,475 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 5, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x1474313c8e50>, <function predictFlux at 0x1474313c8ee0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [2.80551392e+02, 2.85162506e+02, 2.89045563e+02, ...,
          4.08207214e+02, 4.08935272e+02, 4.09784729e+02],
         [2.88803070e+02, 2.94385010e+02, 2.99360291e+02, ...,
          4.20948608e+02, 4.22526123e+02, 4.23982208e+02],
         [2.86376099e+02, 2.93293060e+02, 3.00088348e+02, ...,
          4.39514435e+02, 4.42669708e+02, 4.46309998e+02]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

2023-09-05 18:15:51,037 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 3, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x14f244d53550>, <function predictFlux at 0x14f244d535e0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [-2.77777785e-04, -2.77777785e-04, -2.77777785e-04, ...,
          -2.77777785e-04, -2.77777785e-04, -2.77777785e-04],
         [-2.77777785e-04, -2.77777785e-04, -2.77777785e-04, ...,
          -2.77777785e-04, -2.77777785e-04, -2.77777785e-04],
         [-2.77777785e-04, -2.77777785e-04, -2.77777785e-04, ...,
          -2.77777785e-04
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'variable_out\': length 51 on the data but length 7 on coordinate \'variable_out\'")'

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
2023-09-05 18:17:06,203 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 0, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x153c222f23a0>, <function predictFlux at 0x153be05d40d0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05, -6.94444461e-05, -6.94444461e-05],
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05, -6.94444461e-05, -6.94444461e-05],
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
2023-09-05 18:17:06,619 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 6, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x1474302664c0>, <function predictFlux at 0x1474302665e0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

2023-09-05 18:17:06,683 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 7, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x153c2a12aa60>, <function predictFlux at 0x153c2a12ab80>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [ 1.39068069e+01,  1.33294449e+01,  1.30670853e+01, ...,
           7.50444794e+00,  7.24194336e+00,  7.03221893e+00],
         [ 1.47465286e+01,  1.41691666e+01,  1.39593048e+01, ...,
           7.66194153e+00,  7.39944458e+00,  7.13694763e+00],
         [ 1.61633301e+01,  1.56909714e+01,  1.54811096e+01, ...,
           7.87166595e+00
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

2023-09-05 18:17:07,220 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 1, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x14f1bf9b50d0>, <function predictFlux at 0x14f1bbe73ca0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [1.95122223e+01, 1.79289589e+01, 1.66025009e+01, ...,
          9.37097168e+00, 9.24263763e+00, 9.11416626e+00],
         [1.94694443e+01, 1.79718056e+01, 1.66881256e+01, ...,
          9.24263763e+00, 9.11416626e+00, 8.94305420e+00],
         [1.91698608e+01, 1.79289589e+01, 1.68163910e+01, ...,
          8.90027618e+00, 8.77194214e+00, 8.55791473e+00]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

2023-09-05 18:17:07,581 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 2, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x154a5becddc0>, <function predictFlux at 0x154a5becdee0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [ 4.00766937e+02,  4.01652374e+02,  4.02215820e+02, ...,
           4.34975830e+02,  4.35458893e+02,  4.35941803e+02],
         [ 4.01893890e+02,  4.02698761e+02,  4.03342773e+02, ...,
           4.37309998e+02,  4.37712646e+02,  4.38275970e+02],
         [ 4.02940277e+02,  4.03745148e+02,  4.04469574e+02, ...,
           4.39805420e+02
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
2023-09-05 18:17:08,033 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 3, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x154938f21820>, <function predictFlux at 0x154938f21dc0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [-2.77777785e-04, -2.77777785e-04, -2.77777785e-04, ...,
          -2.77777785e-04, -2.77777785e-04, -2.77777785e-04],
         [-2.77777785e-04, -2.77777785e-04, -2.77777785e-04, ...,
          -2.77777785e-04, -2.77777785e-04, -2.77777785e-04],
         [-2.77777785e-04, -2.77777785e-04, -2.77777785e-04, ...,
          -2.77777785e-04
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

2023-09-05 18:17:08,264 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 5, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x14f2392b18b0>, <function predictFlux at 0x14f2371818b0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [2.80551392e+02, 2.85162506e+02, 2.89045563e+02, ...,
          4.08207214e+02, 4.08935272e+02, 4.09784729e+02],
         [2.88803070e+02, 2.94385010e+02, 2.99360291e+02, ...,
          4.20948608e+02, 4.22526123e+02, 4.23982208e+02],
         [2.86376099e+02, 2.93293060e+02, 3.00088348e+02, ...,
          4.39514435e+02, 4.42669708e+02, 4.46309998e+02]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

2023-09-05 18:17:08,376 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 4, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x147430350310>, <function predictFlux at 0x147430350940>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [3.66786652e+02, 3.63299438e+02, 3.58317230e+02, ...,
          1.64524719e+02, 1.65645554e+02, 1.67264725e+02],
         [3.82977783e+02, 3.79739441e+02, 3.74632782e+02, ...,
          1.74114716e+02, 1.76107498e+02, 1.77851105e+02],
         [3.96054443e+02, 3.93065552e+02, 3.88333344e+02, ...,
          1.88561951e+02, 1.91052780e+02, 1.93792770e+02]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 2000 on coordinate \'time\'")'

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
2023-09-05 18:17:18,842 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-490479303829c0ac78dd175ca6aa1d71', 8, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x153c2a12a5e0>, <function predictFlux at 0x153c2a12a790>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [6.49429860e+01, 6.48050675e+01, 6.49085402e+01, ...,
          6.65975723e+01, 6.84245138e+01, 7.02514563e+01],
         [6.70111756e+01, 6.69767380e+01, 6.70802088e+01, ...,
          6.95620794e+01, 7.18370829e+01, 7.40432682e+01],
         [6.88381271e+01, 6.89415979e+01, 6.90449972e+01, ...,
          7.18715982e+01, 7.43190317e+01, 7.68354177e+01]]
kwargs:    {}
Exception: 'ValueError("conflicting sizes for dimension \'time\': length 51 on the data but length 1000 on coordinate \'time\'")'

[I 2023-09-05 18:17:25.948 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 18:19:17.346 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 18:19:45.194 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 18:19:48.511 ServerApp] Starting buffering for a07084a9-cdbd-48a0-a22d-fd5d4a0aaaa2:c8c009b4-5368-4c4c-883b-61f6dad9429e
[I 2023-09-05 18:19:53.173 ServerApp] Starting buffering for 6b866824-a4c2-4727-8767-086aa96168b9:3b7ba1f1-d2f7-4703-b4a7-72e68c699027
slurmstepd: error: *** JOB 3749872 ON fcn39 CANCELLED AT 2023-09-05T19:11:16 DUE TO TIME LIMIT ***
slurmstepd: error: container_p_join: setns failed for /slurm/3749872/.ns: Invalid argument
slurmstepd: error: container_g_join(3749872): Invalid argument

JOB STATISTICS
==============
Job ID: 3749872
Cluster: snellius
User/Group: qiahan/qiahan
State: TIMEOUT (exit code 0)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:01
CPU Efficiency: 0.00% of 16:01:04 core-walltime
Job Wall-clock time: 01:00:04
Memory Utilized: 55.16 GB
Memory Efficiency: 45.97% of 120.00 GB
